### ISSUE TITLE
run failed: "extensions/extension.proto" is already registered

### ISSUE THREAD

**Issue by zhixiongdu027** [kubernetes-sigs/e2e-framework#155]
Hi all: 
    When I try to run a sample.
    But I am getting the following error and I have not found enough documentation to guide me what to do,
    Can someone teach me, many TKS

```shell
zhixiongdu@deskmini:~/t/framework/e2e$ go mod tidy
zhixiongdu@deskmini:~/t/framework/e2e$ go test . -V
panic: proto: file "extensions/extension.proto" is already registered
        previously from: "github.com/googleapis/gnostic/extensions"
        currently from:  "github.com/google/gnostic/extensions"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict


goroutine 1 [running]:
google.golang.org/protobuf/reflect/protoregistry.glob..func1({0x1651a00, 0x16a7d98}, {0x1651a00, 0xc00042e090})
        /home/zhixiongdu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/reflect/protoregistry/registry.go:54 +0x1f4
google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc0002ebad0, {0x16a7d98, 0xc00037f880})
        /home/zhixiongdu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/reflect/protoregistry/registry.go:128 +0x399
google.golang.org/protobuf/internal/filedesc.Builder.Build({{0x128d6fe, 0x24}, {0x203fcc0, 0x282, 0x282}, 0x0, 0x4, 0x0, 0x0, {0x16628a0, ...}, ...})
        /home/zhixiongdu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/filedesc/build.go:113 +0x1d6
google.golang.org/protobuf/internal/filetype.Builder.Build({{{0x128d6fe, 0x24}, {0x203fcc0, 0x282, 0x282}, 0x0, 0x4, 0x0, 0x0, {0x0, ...}, ...}, ...})
        /home/zhixiongdu/go/pkg/mod/google.golang.org/protobuf@v1.27.1/internal/filetype/build.go:139 +0x198
github.com/google/gnostic/extensions.file_extensions_extension_proto_init()
        /home/zhixiongdu/go/pkg/mod/github.com/google/gnostic@v0.5.7-v3refs/extensions/extension.pb.go:456 +0x198
github.com/google/gnostic/extensions.init.0()
        /home/zhixiongdu/go/pkg/mod/github.com/google/gnostic@v0.5.7-v3refs/extensions/extension.pb.go:388 +0x17
FAIL    e2e     0.014s
FAIL
zhixiongdu@deskmini:~/t/framework/e2e$ 

```

**Comment by Lxrdknows77** [comment]
I have the same problem, but only when I created a new package with the e2e test in a separate folder. But my previous e2e test package still works.

**Comment by Lxrdknows77** [comment]
@zhixiongdu027 Do use use go vendor?

**Comment by vladimirvivien** [comment]
@zhixiongdu027 let us know if that fix worked for you.

**Comment by zhixiongdu027** [comment]
1:  I created a new package with the e2e test in a separate folder. 
2:  copy  [e2e-framework/go.mod](https://github.com/kubernetes-sigs/e2e-framework/blob/main/go.mod) to my folder.
3:  exec go mod tidy 
4:  go build  and it work
